### ISSUE TITLE
is setup.js needed?

### ISSUE THREAD

**Issue by rhagarty** [IBM/procurement-analysis-with-wks#15]
Not sure what purpose this file serves.

**Comment by rameshpoomalai** [comment]
Hi Rich,

This will be called once during installation, it adds following initial data to the Graph DB.
1. The graph by name "procurement" is created in Graph DB. this is required before creating any Node/Vertex

2. Creates the Bootstrap graph, like Continent, Region, Country, Known suppliers, Known locations, Product(MMA),And know port. But this is not the final list, during the document ingest and sync process found any new county/port/supplier i will add to the system. So we are bootstrap with the minimal data.

**Comment by rameshpoomalai** [comment]
without this script we will not be able to add any vertex to the graph db. so this file is required one.
